version: "2.4"
services:
  mysql:
    image: mysql
    restart: unless-stopped
    container_name: todo-db
    ports:
    - 3306:3306
    environment:
      # ultra insecured passwords !
      MYSQL_DATABASE: todo
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
      MYSQL_ROOT_PASSWORD: admin

  keycloak:
    image: quay.io/keycloak/keycloak:10.0.2
    restart: unless-stopped
    container_name: todo-keycloak
    ports:
    - 8180:8080
    environment:
      # ultra insecured passwords !
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
      DB_VENDOR: h2
