quarkus:

  datasource:
    db-kind: mysql
    username: todo
    password: todo
    jdbc:
      url: jdbc:mysql://localhost:3306/todo

  hibernate-orm:
    database:
      generation: none

  flyway:
    migrate-at-start: true

  oidc:
    auth-server-url: http://localhost:8180/auth/realms/quarkus
    client-id: backend-service